# Generated by Django 2.0.7 on 2018-07-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peca',
            options={'verbose_name_plural': 'Transacoes'},
        ),
    ]
