# Generated by Django 2.0.7 on 2018-07-27 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20180726_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computador',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='peca',
            name='computador',
        ),
        migrations.RemoveField(
            model_name='peca',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Computador',
        ),
        migrations.DeleteModel(
            name='Peca',
        ),
    ]
