# Generated by Django 2.0.7 on 2018-07-27 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0004_auto_20180727_2105'),
        ('pedidos', '0004_auto_20180727_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disco_rigido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Disco_rigido')),
                ('fone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Fone')),
                ('gabinete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Gabinete')),
                ('memoria_ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Memoria_ram')),
                ('placa_de_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Placa_de_video')),
                ('placa_mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Placa_mae')),
                ('processadore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Processadore')),
            ],
            options={
                'verbose_name_plural': 'Componentes',
            },
        ),
    ]
