# Generated by Django 2.0.7 on 2018-07-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_componentes_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentes',
            name='cartao_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componentes',
            name='estatos',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
